### ISSUE TITLE
DDN gamma 

### ISSUE THREAD

**Issue by wilk-bit** [jeromerony/fast_adversarial#7]
For neural nets that accept input images in the range [0,255]. The smallest perturbation consists in changing one pixel by 1, corresponding to a norm of 1. Assuming quantization, DDN must achieve a norm lower than 1.5=3/2

Using K steps this implies?
gamma > 1-(3 / 2*eps_0)^(1/K)

also should eps_0 =1 in this scenario?

**Comment by jeromerony** [comment]
Hi! I am not sure what your question is here.
Your reasoning is correct but provides an incoherent results because if the images are in the [0,255] range, then ϵ<sub>0</sub> = 1 means that the perturbation at the first step of the algorithm already has the minimal norm possible (but is not necessarily adversarial).
To obtain the result of γ ≈ 0.05, which corresponds to K = 100, you need to have ϵ<sub>0</sub> = 255 if your images are in the [0,255] range.
Hope this helps!

**Comment by wilk-bit** [comment]
I was confused about eps_0, but you've now answered my question! Thanks for your time and help.
